import "./globals.css"
import { Inter, JetBrains_Mono } from "next/font/google"
import clsx from "clsx"
import { CenteredContainer } from "@/app/components/atoms/CenteredContainer"
import { ButtonToggleThemeMode } from "@/app/components/ButtonToggleThemeMode"
import LayoutProvider from "@/app/providers/layout/provider"

const inter = Inter({ subsets: ["latin"] })
const jetbrains = JetBrains_Mono({ subsets: ["latin"], variable: "--jetbrains" })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, jetbrains.variable)}>
        <LayoutProvider>
          <header className="border-b border-zinc-500">
            <CenteredContainer className="p-4 flex items-center">
              <ButtonToggleThemeMode />
            </CenteredContainer>
          </header>
          {children}
        </LayoutProvider>
      </body>
    </html>
  )
}
